app:
  command:
    base-url: ${CMD_BASE_URL}
  generator:
    output: ${GENERATOR_OUTPUT:./bge-swagger.json}
    generate-enums: ${GENERATOR_GENERATE_ENUM:false}    
    sessionid-as-queryparam: ${GENERATOR_SESSIONID_AS_QUERYPARAM:true}

logging:
  level:
    root: ERROR
    de.witcom: INFO
